/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

/**
 *
 * @author Potro
 */
public class Principal extends javax.swing.JFrame {

    double[] number = new double[2];

    boolean decimal = false;

    boolean divi = false;
    boolean multi = false;
    boolean resta = false;
    boolean suma = false;
    boolean porcentaje = false;

    public Principal() {
        initComponents();
        setResizable(false);//COn este impedimos que la calculadora pueda ser agrandado y deformado
        setSize(330, 540);//Delimito el tamaño que tendra mi calculadora
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_Signo = new javax.swing.JButton();
        btn_Seis = new javax.swing.JButton();
        btn_Porcentaje = new javax.swing.JButton();
        btn_Igual = new javax.swing.JButton();
        btn_Divi = new javax.swing.JButton();
        btn_Mult = new javax.swing.JButton();
        btn_Resta = new javax.swing.JButton();
        btn_Suma = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();
        btn_Siete = new javax.swing.JButton();
        btn_Ocho = new javax.swing.JButton();
        btn_Nueve = new javax.swing.JButton();
        btn_Punto = new javax.swing.JButton();
        btn_Cinco = new javax.swing.JButton();
        btn_Cuatro = new javax.swing.JButton();
        btn_Uno = new javax.swing.JButton();
        btn_Dos = new javax.swing.JButton();
        btn_Tres = new javax.swing.JButton();
        btn_Cero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Jlabel_Ventana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Signo.setBackground(new java.awt.Color(0, 0, 0));
        btn_Signo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Signo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Signo.setText("+/-");
        btn_Signo.setFocusable(false);
        btn_Signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Signo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, 50));

        btn_Seis.setBackground(new java.awt.Color(255, 255, 255));
        btn_Seis.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Seis.setForeground(new java.awt.Color(0, 0, 0));
        btn_Seis.setText("6");
        btn_Seis.setFocusable(false);
        btn_Seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeisActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, 50));

        btn_Porcentaje.setBackground(new java.awt.Color(0, 0, 0));
        btn_Porcentaje.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Porcentaje.setForeground(new java.awt.Color(255, 255, 255));
        btn_Porcentaje.setText("%");
        btn_Porcentaje.setFocusable(false);
        btn_Porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PorcentajeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 70, 50));

        btn_Igual.setBackground(new java.awt.Color(0, 153, 255));
        btn_Igual.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Igual.setForeground(new java.awt.Color(255, 255, 255));
        btn_Igual.setText("=");
        btn_Igual.setFocusable(false);
        btn_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IgualActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 70, 50));

        btn_Divi.setBackground(new java.awt.Color(0, 153, 255));
        btn_Divi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Divi.setForeground(new java.awt.Color(255, 255, 255));
        btn_Divi.setText("/");
        btn_Divi.setFocusable(false);
        btn_Divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DiviActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Divi, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 20, 70, 50));

        btn_Mult.setBackground(new java.awt.Color(0, 153, 255));
        btn_Mult.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Mult.setForeground(new java.awt.Color(255, 255, 255));
        btn_Mult.setText("*");
        btn_Mult.setFocusable(false);
        btn_Mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 70, 50));

        btn_Resta.setBackground(new java.awt.Color(0, 153, 255));
        btn_Resta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Resta.setForeground(new java.awt.Color(255, 255, 255));
        btn_Resta.setText("-");
        btn_Resta.setFocusable(false);
        btn_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RestaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 70, 50));

        btn_Suma.setBackground(new java.awt.Color(0, 153, 255));
        btn_Suma.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Suma.setForeground(new java.awt.Color(255, 255, 255));
        btn_Suma.setText("+");
        btn_Suma.setFocusable(false);
        btn_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SumaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 70, 50));

        btn_Borrar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Borrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Borrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Borrar.setText("AC");
        btn_Borrar.setFocusable(false);
        btn_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 50));

        btn_Siete.setBackground(new java.awt.Color(255, 255, 255));
        btn_Siete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Siete.setForeground(new java.awt.Color(0, 0, 0));
        btn_Siete.setText("7");
        btn_Siete.setFocusable(false);
        btn_Siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SieteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 50));

        btn_Ocho.setBackground(new java.awt.Color(255, 255, 255));
        btn_Ocho.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Ocho.setForeground(new java.awt.Color(0, 0, 0));
        btn_Ocho.setText("8");
        btn_Ocho.setFocusable(false);
        btn_Ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OchoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 50));

        btn_Nueve.setBackground(new java.awt.Color(255, 255, 255));
        btn_Nueve.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Nueve.setForeground(new java.awt.Color(0, 0, 0));
        btn_Nueve.setText("9");
        btn_Nueve.setFocusable(false);
        btn_Nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NueveActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 70, 50));

        btn_Punto.setBackground(new java.awt.Color(255, 255, 255));
        btn_Punto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Punto.setForeground(new java.awt.Color(0, 0, 0));
        btn_Punto.setText(".");
        btn_Punto.setFocusable(false);
        btn_Punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PuntoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 80, 50));

        btn_Cinco.setBackground(new java.awt.Color(255, 255, 255));
        btn_Cinco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Cinco.setForeground(new java.awt.Color(0, 0, 0));
        btn_Cinco.setText("5");
        btn_Cinco.setFocusable(false);
        btn_Cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CincoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 70, 50));

        btn_Cuatro.setBackground(new java.awt.Color(255, 255, 255));
        btn_Cuatro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Cuatro.setForeground(new java.awt.Color(0, 0, 0));
        btn_Cuatro.setText("4");
        btn_Cuatro.setFocusable(false);
        btn_Cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CuatroActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 50));

        btn_Uno.setBackground(new java.awt.Color(255, 255, 255));
        btn_Uno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Uno.setForeground(new java.awt.Color(0, 0, 0));
        btn_Uno.setText("1");
        btn_Uno.setFocusable(false);
        btn_Uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UnoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, 50));

        btn_Dos.setBackground(new java.awt.Color(255, 255, 255));
        btn_Dos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Dos.setForeground(new java.awt.Color(0, 0, 0));
        btn_Dos.setText("2");
        btn_Dos.setFocusable(false);
        btn_Dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 70, 50));

        btn_Tres.setBackground(new java.awt.Color(255, 255, 255));
        btn_Tres.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Tres.setForeground(new java.awt.Color(0, 0, 0));
        btn_Tres.setText("3");
        btn_Tres.setFocusable(false);
        btn_Tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TresActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 70, 50));

        btn_Cero.setBackground(new java.awt.Color(255, 255, 255));
        btn_Cero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Cero.setForeground(new java.awt.Color(0, 0, 0));
        btn_Cero.setText("0");
        btn_Cero.setFocusable(false);
        btn_Cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CeroActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 181, 327, 350));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Estandar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Jlabel_Ventana.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Jlabel_Ventana.setForeground(new java.awt.Color(0, 0, 0));
        Jlabel_Ventana.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(Jlabel_Ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 300, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarActionPerformed
        Jlabel_Ventana.setText("");
        decimal = false;

        divi = false;
        multi = false;
        resta = false;
        suma = false;
        porcentaje = false;
    }//GEN-LAST:event_btn_BorrarActionPerformed

    private void btn_SignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignoActionPerformed
        try{
            double change;
            String entero;
            change = Double.parseDouble(Jlabel_Ventana.getText());
            change = change * -1;
            if(change % 1 == 0){
                    entero = Double.toString(change);
                    Jlabel_Ventana.setText(entero.substring(0, entero.length() - 2));
                }else{
                         Jlabel_Ventana.setText(Double.toString(change));
                    }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btn_SignoActionPerformed

    private void btn_PorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PorcentajeActionPerformed
        try {
            number[0] = Double.parseDouble(Jlabel_Ventana.getText());//Guardamos el dato
            Jlabel_Ventana.setText("");//Borramos el Texto
            porcentaje = true;//Evaluando el booleano
            decimal = true;//Una vez guardado el valor se evalua el bool
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_PorcentajeActionPerformed

    //*************************************************************************** 

    private void btn_SieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SieteActionPerformed
        Jlabel_Ventana.setText(Jlabel_Ventana.getText() + "7");
    }//GEN-LAST:event_btn_SieteActionPerformed

    private void btn_OchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OchoActionPerformed
        Jlabel_Ventana.setText(Jlabel_Ventana.getText() + "8");
    }//GEN-LAST:event_btn_OchoActionPerformed

    private void btn_NueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NueveActionPerformed
        Jlabel_Ventana.setText(Jlabel_Ventana.getText() + "9");
    }//GEN-LAST:event_btn_NueveActionPerformed

    private void btn_CuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CuatroActionPerformed
        Jlabel_Ventana.setText(Jlabel_Ventana.getText() + "4");
    }//GEN-LAST:event_btn_CuatroActionPerformed

    private void btn_CincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CincoActionPerformed
        Jlabel_Ventana.setText(Jlabel_Ventana.getText() + "5");
    }//GEN-LAST:event_btn_CincoActionPerformed

    private void btn_SeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeisActionPerformed
        Jlabel_Ventana.setText(Jlabel_Ventana.getText() + "6");
    }//GEN-LAST:event_btn_SeisActionPerformed

    private void btn_UnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UnoActionPerformed
        Jlabel_Ventana.setText(Jlabel_Ventana.getText() + "1");
    }//GEN-LAST:event_btn_UnoActionPerformed

    private void btn_DosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DosActionPerformed
        Jlabel_Ventana.setText(Jlabel_Ventana.getText() + "2");
    }//GEN-LAST:event_btn_DosActionPerformed

    private void btn_TresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TresActionPerformed
        Jlabel_Ventana.setText(Jlabel_Ventana.getText() + "3");
    }//GEN-LAST:event_btn_TresActionPerformed

    private void btn_CeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CeroActionPerformed
        Jlabel_Ventana.setText(Jlabel_Ventana.getText() + "0");
    }//GEN-LAST:event_btn_CeroActionPerformed

    private void btn_PuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PuntoActionPerformed
        if (decimal == false) {
            Jlabel_Ventana.setText(Jlabel_Ventana.getText() + ".");
            decimal = true;
        }
    }//GEN-LAST:event_btn_PuntoActionPerformed

    //************************************************************************** 

    private void btn_DiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DiviActionPerformed
        try {
            number[0] = Double.parseDouble(Jlabel_Ventana.getText());//Guardamos el dato
            Jlabel_Ventana.setText("");//Borramos el Texto
            divi = true;//Evaluando el booleano
            decimal = true;//Una vez guardado el valor se evalua el bool
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_DiviActionPerformed

    private void btn_MultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultActionPerformed
        try {
            number[0] = Double.parseDouble(Jlabel_Ventana.getText());
            Jlabel_Ventana.setText("");
            multi = true;
            decimal = true;
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_MultActionPerformed

    private void btn_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RestaActionPerformed
        try {
            number[0] = Double.parseDouble(Jlabel_Ventana.getText());
            Jlabel_Ventana.setText("");
            resta = true;
            decimal = true;
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_RestaActionPerformed

    private void btn_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SumaActionPerformed
        try {
            number[0] = Double.parseDouble(Jlabel_Ventana.getText());
            Jlabel_Ventana.setText("");
            suma = true;
            decimal = true;
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_SumaActionPerformed

    private void btn_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IgualActionPerformed
        Double resultado;
        String entero;
        try {
            number[1] = Double.parseDouble(Jlabel_Ventana.getText());

            if (divi == true) {
                if (number[1] == 0) {
                    Jlabel_Ventana.setText("Error");
                } else {
                    resultado = number[0] / number[1];
                if(resultado % 1 == 0){
                    entero = Double.toString(resultado);
                    Jlabel_Ventana.setText(entero.substring(0, entero.length() - 2));
                }else{
                         Jlabel_Ventana.setText(Double.toString(resultado));
                    }
                    
                }
                

            } else if (multi == true) {
                resultado = number[0] * number[1];
                if(resultado % 1 == 0){
                    entero = Double.toString(resultado);
                    Jlabel_Ventana.setText(entero.substring(0, entero.length() - 2));
                }else{
                         Jlabel_Ventana.setText(Double.toString(resultado));
                    }
            } else if (resta == true) {
                resultado = number[0] - number[1];
                if(resultado % 1 == 0){
                    entero = Double.toString(resultado);
                    Jlabel_Ventana.setText(entero.substring(0, entero.length() - 2));
                }else{
                         Jlabel_Ventana.setText(Double.toString(resultado));
                    }
            } else if (suma == true) {
                resultado = number[0] + number[1];
               if(resultado % 1 == 0){
                    entero = Double.toString(resultado);
                    Jlabel_Ventana.setText(entero.substring(0, entero.length() - 2));
                }else{
                         Jlabel_Ventana.setText(Double.toString(resultado));
                    }
            }else if(porcentaje = true){
                resultado = number[0] * (number[0]/100.0);
                if(resultado % 1 == 0){
                    entero = Double.toString(resultado);
                    Jlabel_Ventana.setText(entero.substring(0, entero.length() - 2));
                }else{
                         Jlabel_Ventana.setText(Double.toString(resultado));
                    }
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_IgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_Ventana;
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Cero;
    private javax.swing.JButton btn_Cinco;
    private javax.swing.JButton btn_Cuatro;
    private javax.swing.JButton btn_Divi;
    private javax.swing.JButton btn_Dos;
    private javax.swing.JButton btn_Igual;
    private javax.swing.JButton btn_Mult;
    private javax.swing.JButton btn_Nueve;
    private javax.swing.JButton btn_Ocho;
    private javax.swing.JButton btn_Porcentaje;
    private javax.swing.JButton btn_Punto;
    private javax.swing.JButton btn_Resta;
    private javax.swing.JButton btn_Seis;
    private javax.swing.JButton btn_Siete;
    private javax.swing.JButton btn_Signo;
    private javax.swing.JButton btn_Suma;
    private javax.swing.JButton btn_Tres;
    private javax.swing.JButton btn_Uno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
